### ISSUE TITLE
Technical Issue #4: Making Links More Visible

### ISSUE THREAD

**Issue by ronaldliujr** [nicoleedwardsp/MyPersonalWebsite#7]
I think that overall, your website is very well done. However, many of your links right now do not highlight or underline when they are hovered over or clicked on. I think that this simple change to links in your nav bar and other places, like the one in the screenshot below, could really enhance your overall website, especially on the user experience/interaction side. 

![image](https://user-images.githubusercontent.com/112499621/201489179-7cccd31c-9a91-4749-8a63-444006f856f9.png)

**Comment by nicoleedwardsp** [comment]
Another great suggestion! I changed the buttons and links to be blue when you hover them.
