### ISSUE TITLE
Content Issue #3: White Font

### ISSUE THREAD

**Issue by ronaldliujr** [nicoleedwardsp/MyPersonalWebsite#8]
https://github.com/nicoleedwardsp/MyPersonalWebsite/blob/ff38449c27fbc637625c8978e2672a23fde0f0c4/index.html#L34

I love the overall look of your website, however, I do feel like it is a bit difficult to read the "art that sets you apart" in the middle of the picture. The picture itself is already quite light, and I feel like the white font blends in with the art a bit.

![image](https://user-images.githubusercontent.com/112499621/201489274-cd509f46-6a21-4e11-bce6-afce2111069a.png)

**Comment by nicoleedwardsp** [comment]
That's a great suggestion, Ronald! Thank you. I changed the background to an image that did not have that much white in it.
