### ISSUE TITLE
Content Issue #4: Large Picture in Sitemap

### ISSUE THREAD

**Issue by ronaldliujr** [nicoleedwardsp/MyPersonalWebsite#9]
https://github.com/nicoleedwardsp/MyPersonalWebsite/blob/ff38449c27fbc637625c8978e2672a23fde0f0c4/sitemap.html#L50

For your sitemap page, I think that the photo is a bit too large. If I didn't know what a sitemap was, I'm not sure I would have necessarily known to scroll down to see the rest of the page. I think by making the photo a bit smaller, this allows the links to be shown earlier, thus letting users know that there is more content. I also think that you could add a bit more to the sitemap, maybe adding a few links to where people can go see the artists paintings in person.

![image](https://user-images.githubusercontent.com/112499621/201489339-9e2d1b38-1bb1-4b8a-9ddb-dfd57eade29f.png)

**Comment by nicoleedwardsp** [comment]
Also great idea. I made the picture smaller :) thanks!
